### ISSUE TITLE
How to execute the program?

### ISSUE THREAD

**Issue by damiendevienne** [cwhidden/uspr#1]
Hello, 
Very nice paper discovered on Arxiv today. 
I managed to download and compile your code but could not execute it. 
What would be the basic command for computing uSPR between two trees? 
Thanks a lot, 

D

**Comment by cwhidden** [comment]
Hello Damien,

I've just released the first version of uspr which includes documentation. Please have a look at the new README, I would appreciate any comments.

uspr takes pairs of binary unrooted trees in newick format as input, one tree per line.  For example, consider the test file test_trees/replug_example_3.tre:

```
(a1,(a2,(a3,(a4,(b1,(b2,(b3,(b4,(c1,(c2,(c3,c4)))))))))));
(a4,(a3,(a2,(a1,(b4,((b1,b2),(b3,(c1,(c2,(c3,c4))))))))));
```

You can run uspr with this file like so:

```
./uspr < test_trees/replug_example_3.tre
T1: (a1,a2,(a3,(a4,(b1,(b2,(b3,(b4,(c1,(c2,(c3,c4))))))))));
T2: (a1,(a2,(a3,a4)),(((b1,b2),(b3,(c1,(c2,(c3,c4))))),b4));
a_TBR: 2 <= d_TBR <= 6
{2}
d_TBR = 2
F1: ((a1,a2),a3,a4); (b1,b2); (b3,(((c3,c4),c2),c1),b4);
F2: ((a1,a2),a3,a4); (b4,(((c3,c4),c2),c1),b3); (b1,b2);
{2} {3}
d_R = 3
F1: ((a1,a2),a3,a4); (b1,b2,(b3,b4)); ((*,c1),(c3,c4),c2);
F2: ((a1,a2),a3,a4); ((b3,b4),b1,b2); ((*,c1),(c3,c4),c2);
examined 347 trees
d_USPR = 3
```

**Comment by damiendevienne** [comment]
Thanks a lot, I'll look at that, 

Best,
D
