### ISSUE TITLE
Compilation error with make

### ISSUE THREAD

**Issue by damiendevienne** [cwhidden/uspr#2]
Hello, 
I tried to compile uspr with the `make` command but got the following errors: 

tbr.h:417:184: error: redeclaration of ‘template<class T> int tbr_distance_hlpr(uforest&, uforest&, int, T, int (_)(uforest&, uforest&, nodemapping&, int, T), uforest__, uforest__)’ may not have default arguments [-fpermissive]
 int tbr_distance_hlpr(uforest &T1, uforest &T2, int k, T t, int (_func_pointer)(uforest &F1, uforest &F2, nodemapping &twins, int k, T s), uforest *_MAF1 = NULL, uforest *_MAF2 = NULL) {

tbr.h:467:257: error: redeclaration of ‘template<class T> int tbr_distance_hlpr(uforest&, uforest&, int, nodemapping&, std::map<int, int>&, std::__cxx11::list<int>&, T, int (_)(uforest&, uforest&, nodemapping&, int, T), uforest__, uforest__)’ may not have default arguments [-fpermissive]
 st &F1, uforest &F2, int k, nodemapping &twins, map<int, int> &sibling_pairs, list<int> &singletons, T t, int (_func_pointer)(uforest &F1, uforest &F2, nodemapping &twins, int k, T s), uforest *_MAF1 = NULL, uforest *_MAF2 = NULL) {

Makefile:29: recipe for target 'uspr' failed
make: **\* [uspr] Error 1

Any idea?

**Comment by damiendevienne** [comment]
OK, found it myself. 
line 417 and 467 of `tbr.h`, in the decleration of the function arguments, the default NULL should not be defined. 
You should replace 

``` cpp
uforest **MAF1 = NULL, uforest **MAF2 = NULL
```

by

``` cpp
uforest **MAF1/* = NULL*/, uforest **MAF2 /*= NULL*/
```

D

**Comment by cwhidden** [comment]
Hi Damien,

Thanks for pointing this out. I'm surprised it compiled fine on my test systems.

I've just pushed a new version. Can you please verify that you can compile uspr fine now?

Thanks,

Chris

**Comment by damiendevienne** [comment]
Hi, 
It's ok it works now.
